### ISSUE TITLE
TypeError: URL.canParse is not a function

### ISSUE THREAD

**Issue by BHDBvde** [modernweb-dev/web#2746] opened 2024-06-03 07:48 UTC
When using a URL.canParse in code, running a test with the latest version of web-test-runner gives me this error:

TypeError: URL.canParse is not a function

Used node version: >20

Why is this not working?

**Comment by bashmish** [comment] 2024-06-03 09:10
it's a recent feature that requires a polyfill in some browsers https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static

if you only test in latest browsers, maybe just update your dependencies to use the latest
![image](https://github.com/modernweb-dev/web/assets/137844/872c35ac-7a49-40de-bdde-6efe06c10f51)

alternatively, you can add a polyfill, check this README https://github.com/modernweb-dev/web/tree/master/packages/dev-server-polyfill

I think we can close this since this is not a bug

**Closed by bashmish** 2024-06-03 09:10 UTC
