### ISSUE TITLE
Tests do not finish or hangs when asserting window - structuredClone errors

### ISSUE THREAD

**Issue by josephsintum** [modernweb-dev/web#2802] opened 2024-09-05 18:15 UTC
When asserting with and object that contains or reference the window, the test never finish and in the browser it show a structuredClone error in the test framework 
Here's a test case
```js
import { expect } from '@esm-bundle/chai';

describe('suite', function () {
    it('window test', () => {
        let cloneWindow = window.Window;
        expect(cloneWindow).to.be.a('object');
    });
});
```

The test finishes but gets stuck, in the CLI, there are no errors but in the browser, you can see this error message `DataCloneError: Failed to execute 'structuredClone' on 'Window': function Window() { [native code] } could not be cloned. at stable (__web-dev-server__web-socket.js:23:24)` 

<img width="760" alt="Screenshot 2024-09-05 at 11 02 38" src="https://github.com/user-attachments/assets/0b5ebb34-a694-45d6-9c98-613e63e606dd">

**Comment by lucaelin** [comment] 2024-09-06 22:48
This is related to #2728 and #2731 , maybe some check is required for special cases like window, document and such or the other way around?

**Comment by denilsonsa** [comment] 2024-09-10 11:57
I'm getting the same error, but with a slightly different error:

```
DOMException: Failed to execute 'structuredClone' on 'Window': function proxy(a, b) {
                return p.invoke(func, this, slice(arguments));
            } could not be cloned.
```

A quick and dirty pseudo-solution:

```diff
--- node_modules/@web/dev-server-core/dist/web-sockets/webSocketsPlugin.js.bak	2024-09-10 13:52:55
+++ node_modules/@web/dev-server-core/dist/web-sockets/webSocketsPlugin.js	2024-09-10 13:48:32
@@ -38,7 +38,12 @@
         }

         export function stable (obj, replacer, spacer) {
-          var target = structuredClone(obj)
+          var target;
+          try {
+            target = structuredClone(obj)
+          } catch (e) {
+            target = obj;
+          }
           var tmp = deterministicDecirc(target, '', [], undefined) || target
           var res
           if (replacerStack.length === 0) {
```

This isn't production code, but at least it lets my tests report correctly, which is much better than waiting for two minutes for a random timeout on a test code that can't timeout.

As a side note, I see the upstream code has been updated over time. [The function name `stable` has been replaced 6½ years ago](https://github.com/davidmarkclements/fast-safe-stringify/commit/6f724925560bbf65d036f35f34c6ce4d50501e74).

**Comment by laino** [comment] 2024-09-16 06:38
The root cause appears to be that Chai's ``AssertionError`` has an ``actual`` property, which contains the actual object. This error is in the data structure that we attempt to serialize:

![swappy-20240916_083339](https://github.com/user-attachments/assets/7e00835f-c46b-443a-9aa9-09e9f9b8ca62)

Obviously this is going to go badly if there's anything in there that can't be cloned. I believe this is the problematic line: https://github.com/modernweb-dev/web/blob/d5ae228f1f030a58995ac5ac5c51df4e02612981/packages/test-runner-mocha/src/collectTestResults.ts#L49

**Comment by bashmish** [comment] 2024-10-10 11:17
> I think this is a duplicate of #2772 which I was made aware of

Indeed, I'll close this one and invite everyone to discuss it in #2772

**Closed by bashmish** 2024-10-10 11:17 UTC
