### ISSUE TITLE
[dev-server] React + Typescript: Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by theisgroenbech** [modernweb-dev/web#1862] opened 2022-01-26 09:45 UTC
I have tried to use the example in [example-projects](https://github.com/modernweb-dev/example-projects/tree/master/react-tsx) with React Router.

I have cloned the example, installed `react-router-dom` and used it in `App.tsx`.

When running the server and navigating to `/demo/` it fails with: `Uncaught ReferenceError: process is not defined`

I have created a repository with the problem: https://github.com/theisgroenbech/web-dev-server-example/

![image](https://user-images.githubusercontent.com/25243461/151140062-1c4d5657-1328-466d-8060-8de0c3f5d6c9.png)

Any ideas?

**Comment by romanzy-1612** [comment] 2022-06-13 23:41
Put this before loading any javascript into your html file:
```
    <script>
      globalThis.process = { env: { NODE_ENV: 'development' } };
    </script>
```

When bundling with rollup use @rollup/plugin-replace in order to remove development from your modules

**Comment by web-padawan** [comment] 2022-10-20 10:29
See https://github.com/modernweb-dev/web/issues/1954#issuecomment-1285280464 for a working config using `@rollup/plugin-replace` to provide `process.env.NODE_ENV`.
Closing as this is not a bug. We could consider updating [example projects](https://github.com/modernweb-dev/example-projects) accordingly, though.

**Closed by web-padawan** 2022-10-20 10:29 UTC
