### ISSUE TITLE
[dev-server-storybook] v1 published files are wrong format

### ISSUE THREAD

**Issue by jorenbroekema** [modernweb-dev/web#2405] opened 2023-08-03 10:01 UTC
Since v1 of web dev server storybook, it no longer works due to wrong file formats.

```
> wds --config .storybook/server.config.mjs

file:///path/to/node_modules/@web/dev-server-storybook/index.mjs:2
import cjsEntrypoint from './dist/index.js';
       ^^^^^^^^^^^^^
SyntaxError: The requested module './dist/index.js' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

Main MJS entrypoint points to `index.mjs`:
```
// this file is autogenerated with the generate-mjs-dts-entrypoints script
import cjsEntrypoint from './dist/index.js';

const { storybookPlugin } = cjsEntrypoint;

export { storybookPlugin };
```

This is attempting to import a default import from a CJS file, which makes no sense:
- Why would MJS import from a CJS file
- There is no default export in that file, only named

I think something might have gone wrong in your build process in the v1 publish

**Comment by thepassle** [comment] 2023-08-03 10:03
@koddsson worked on this in https://github.com/modernweb-dev/web/pull/2391, can you take a look kris?

**Comment by koddsson** [comment] 2023-08-04 07:04
Weird! I would have thought that the outputted code would be an ES Module due to the `"module": "nodenext"` setting in the `tsconfig.json` 🤔 

In any case, I should have double-checked this before publishing..

**Comment by koddsson** [comment] 2023-08-04 08:11
@thepassle; how does this look?

https://github.com/modernweb-dev/web/pull/2407

**Comment by Westbrook** [comment] 2023-08-04 12:54
In this case `generate-mjs-dts-entrypoints` is still generating the `index.mjs`, which is also the default entry point via the `exports` field in `package.json`...

**Comment by koddsson** [comment] 2023-08-04 13:19
> In this case `generate-mjs-dts-entrypoints` is still generating the `index.mjs`, which is also the default entry point via the `exports` field in `package.json`...

Weird. It errors when I run it locally. When is this script run? I would expect to see it fail in CI then as well if it's supposed to be run before publishing but I haven't seen anything fail 🤔

**Comment by koddsson** [comment] 2023-08-17 17:50
Hey! Has this been fixed in @web/dev-server-storybook@1.0.2 for y'all?

**Comment by Westbrook** [comment] 2023-08-18 00:51
Now I run into:
```
file:///root/project/node_modules/@web/dev-server-storybook/dist/build/rollup/createRollupConfig.js:4
import html from '@web/rollup-plugin-html';
       ^^^^
SyntaxError: The requested module '@web/rollup-plugin-html' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
error Command failed with exit code 1.
```
When trying to build the Storybook for publication. Need to dig in some more.

**Comment by Westbrook** [comment] 2023-08-18 00:53
Actually, it seems there's a good amount of CJS-ism remaining in `@web/dev-server-storybook/dist/build/rollup/createRollupConfig.js` 🤔

**Comment by koddsson** [comment] 2023-08-19 18:06
> Actually, it seems there's a good amount of CJS-ism remaining in `@web/dev-server-storybook/dist/build/rollup/createRollupConfig.js` 🤔

Weird, I can't see any and I was able to get a storybook project up and running. Can you put together a little reproduction project @Westbrook ?

**Comment by Westbrook** [comment] 2023-08-23 20:36
I'm able to repro with this: https://github.com/Westbrook/wds-storybook-test

- clone it
- `yarn` it
- run `yarn storybook:build`
- see:
```
╰─ yarn storybook:build
yarn run v1.22.19
$ tsc && npm run analyze -- --exclude dist && build-storybook

> test-el@0.0.0 analyze
> cem analyze --litelement --exclude dist

[4:34:33 PM] @custom-elements-manifest/analyzer: Created new manifest.
file:///Users/westbrookjohnson/Documents/repos/test-el/node_modules/@web/dev-server-storybook/dist/build/rollup/createRollupConfig.js:4
import html from '@web/rollup-plugin-html';
       ^^^^
SyntaxError: The requested module '@web/rollup-plugin-html' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Separately, the use of the new MDX version seems to require `@types/react` to build. Seems like a bug on MDX's side...but we might want to include on our end to smooth the process?

**Comment by bashmish** [comment] 2023-08-24 08:44
I wouldn't go to MDX v2 simultaneously as I explained in https://github.com/modernweb-dev/web/pull/2415#discussion_r1294591953

**Comment by koddsson** [comment] 2023-08-24 09:25
Ah this MDX stuff is annoying. Not sure how to actually solve that. If we downgrade MDX we need to make another breaking change right?

The other stuff should be fixed in https://github.com/modernweb-dev/web/pull/2423

**Comment by Westbrook** [comment] 2023-08-24 20:37
We could down grade without a break, if it’s possible. None of the breaking version’s releases have worked yet. 😖

Or if it worked, can we add those types as normal dependencies of wds-storybook and call it a day?

**Comment by koddsson** [comment] 2023-08-28 12:37
> We could down grade without a break, if it’s possible. None of the breaking version’s releases have worked yet. 😖

Ahh, then I might just save us the headache and downgrade.

**Comment by Westbrook** [comment] 2023-08-30 00:05
More fun issues... `dist` is not being published: https://unpkg.com/browse/@web/dev-server-storybook@1.0.3/ 😢

**Comment by koddsson** [comment] 2023-08-30 07:31
So weird. This should fix it: https://github.com/modernweb-dev/web/pull/2432

**Comment by Westbrook** [comment] 2023-08-31 20:01
We're having a quick chat in https://github.com/modernweb-dev/web/issues/2025#issuecomment-1701242703 and https://github.com/modernweb-dev/web/pull/2437 about future possibilities here. Not that that thinking won't be key to the effort, but it might put us in a more flexible future-facing position with Storybook at large.

**Comment by koddsson** [comment] 2023-09-01 06:09
> Progress, but not quite success?

I'm trying to reproduce this but I can't in `Westbrook/wds-storybook-test`:

```sh
 ~/src/koddsson/wds-storybook-test/ [main*] npm run build

> test-el@0.0.0 build
> tsc && npm run analyze -- --exclude dist


> test-el@0.0.0 analyze
> cem analyze --litelement --exclude dist

[8:07:33 AM] @custom-elements-manifest/analyzer: Created new manifest.
```

**Comment by Westbrook** [comment] 2023-09-01 11:27
I just updated https://github.com/Westbrook/wds-storybook-test and it shows me that same MDX issue. Can you check again?

If not, maybe there's something about your local system that's an important difference. Node version of something?

**Comment by koddsson** [comment] 2023-09-04 07:57
Maybe `v1.0.5` will be the one that works? :D

**Comment by koddsson** [comment] 2023-09-05 13:21
@Westbrook; have you had a chance to look at the latest version?

**Comment by Westbrook** [comment] 2023-09-05 18:05
Looks like we're finally OK here. Working through some final things in CI, but the telltale issues we'd been going back and forth between seem to be cleaned up now!

**Comment by Westbrook** [comment] 2023-09-06 21:37
Looks good on my end. We've merged this version to `main`, so I'm ready to close this. Please open a new issue with additional reproduction steps if you find this or similar situations arise in your consumption.

**Closed by Westbrook** 2023-09-06 21:37 UTC
